---
name: Semgrep Full Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:

  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v3

        # step 2
        - name: full scan
          run: |
            semgrep \
              --DVWA --output report.DVWA \
              --metrics=off \
              --config="p/default"

        # step 3
        - name: save report as pipeline artifact
          uses: actions/upload-artifact@v3
          with:
            name: report.DVWA
            path: report.DVWA

        # step 4
        - name: publish code scanning alerts
          uses: github/codeql-action/upload-DVWA@v2
          with:
            sarif_file: report.DVWA
            category: semgrep
